require:
  - "rubocop-rails"
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "tmp/**/*"

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Layout/ClassStructure:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/schema.rb

Layout/LeadingCommentSpace:
  Exclude:
    - bin/*

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
  AllowedPatterns: ['\A\s*#'] # To exclude this cop from comments
  Exclude:
    - bin/bundle

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true
  IgnoreLiteralBranches: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: true

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or a Float.
  Max: 16
  Exclude:
    - bin/bundle
    - app/controllers/api/v1/application_controller.rb

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - lib/tasks/auto_annotate_models.rake
    - config/**/*
    - components/*/spec/**/*
    - spec/**/*
    - db/migrate/*
    - db/schema.rb

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false
  Max: 250

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6
  Exclude:
    - bin/bundle

Metrics/MethodLength:
  CountComments: false
  Max: 24

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Naming/VariableNumber:
  Enabled: false

NotNullColumn:
  Enabled: false

Rails:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/ApplicationController:
  Enabled: false

Rails/Delegate:
  Enabled: true

Rails/Exit:
  Exclude:
    - lib/tasks/**/*

Rails/FilePath:
  Enabled: false

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Output:
  Exclude:
    - lib/tasks/**/*

Rails/Present:
  Enabled: true
  Exclude:
    - bin/bundle

Rails/Pluck:
  Enabled: true

Rails/PluckId:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ReversibleMigration:
  Exclude:
    - db/migrate/20231118033656_add_status_relationship_purchase_order.rb

Rails/SaveBang:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:

Rails/WhereExists:
  Enabled: true

RSpec:
  Enabled: false

RSpec/Rails/AvoidSetupHook:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: true

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/AndOr:
  EnforcedStyle: conditionals

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - db/schema.rb

Style/GlobalStdStream:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumericLiterals:
  Enabled: true
  Exclude:
    - db/schema.rb

Style/OptionalBooleanParameter:
  Enabled: false

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/SpecialGlobalVars:
  Exclude:
    - bin/bundle

Style/StringChars:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/StringLiterals:
  Exclude:
    - db/schema.rb

Style/SwapValues:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
